### ISSUE TITLE
No LoRA model list [dev branch]

### ISSUE THREAD

**Issue by ItsSkynet** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#211] opened 2024-01-01 11:10 UTC
Using dev branch, No LoRA model list loads/refresh if they are inside subfolders.

Placing a LoRA safetensor file in the root of the "Lora" folder makes that particular LoRA safetensor to appear on refresh.
It seems that the refresh function doesn't expect LoRA files to be inside subfolders.

**Comment by contentis** [comment] 2024-01-02 08:53
For now, this is expected behaviour and won't be fixed due to other priorities.

**Closed** 2024-01-10 02:23 UTC
Labels: wontfix

**Comment by Paul-Williams** [comment] 2024-01-14 17:06
This is unfortunate to hear

**Comment by PabloMontero** [comment] 2024-01-30 13:31
I noticed list is not working for whom, like me, has the Lora folder relocated externally via webui-user.bat with argument like -`-lora-dir "C:\AI\SD_Models\Lora" `
