### ISSUE TITLE
4090 get CUDA out of memory

### ISSUE THREAD

**Issue by daxijiu** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#64] opened 2023-10-19 02:16 UTC
I success generation a SDXL engine （use webui dev ）
when I try to generation a picture，an error occurred when the inference progress bar reached around 40% (10/25 steps). The error message is as follows.
（my system sd_xl_base_1.0_0.9vae_fp16fix，DPM++ 2M SDE Karras，25 steps，1024×1024，win10，drvier version 531.61）
By the way, the SD1.5 engine can be used normally.
=========
To create a public link, set `share=True` in `launch()`.
Startup time: 20.2s (prepare environment: 2.5s, import torch: 4.5s, import gradio: 0.4s, setup paths: 0.5s, initialize shared: 0.2s, other imports: 0.3s, load scripts: 2.4s, create ui: 5.1s, gradio launch: 4.2s).
Activating unet: [TRT] sd_xl_base_1.0_0.9vae_fp16fix
Loading TensorRT engine: D:\kkkkk\release\SD_webui_with_aki_launcher_dev\models\Unet-trt\sd_xl_base_1.0_0.9vae_fp16fix_75679766_cc89_sample=2x4x128x128-timesteps=2-encoder_hidden_states=2x77x2048-y=2x2816.trt
[W] 'colored' module is not installed, will not use colors when logging. To enable colors, please install the 'colored' module: python3 -m pip install colored
[I] Loading bytes from D:\kkkkk\release\SD_webui_with_aki_launcher_dev\models\Unet-trt\sd_xl_base_1.0_0.9vae_fp16fix_75679766_cc89_sample=2x4x128x128-timesteps=2-encoder_hidden_states=2x77x2048-y=2x2816.trt
Profile 0:
	sample = [(2, 4, 128, 128), (2, 4, 128, 128), (2, 4, 128, 128)]
	timesteps = [(2,), (2,), (2,)]
	encoder_hidden_states = [(2, 77, 2048), (2, 77, 2048), (2, 77, 2048)]
	y = [(2, 2816), (2, 2816), (2, 2816)]
	latent = [(2, 4, 128, 128), (2, 4, 128, 128), (2, 4, 128, 128)]

Loading TensorRT engine: D:\kkkkk\release\SD_webui_with_aki_launcher_dev\models\Unet-trt\sd_xl_base_1.0_0.9vae_fp16fix_75679766_cc89_sample=1x4x96x96+2x4x128x128+8x4x128x128-timesteps=1+2+8-encoder_hidden_states=1x77x2048+2x77x2048+8x154x2048-y=1x2816+2x2816+8x2816.trt
[I] Loading bytes from D:\kkkkk\release\SD_webui_with_aki_launcher_dev\models\Unet-trt\sd_xl_base_1.0_0.9vae_fp16fix_75679766_cc89_sample=1x4x96x96+2x4x128x128+8x4x128x128-timesteps=1+2+8-encoder_hidden_states=1x77x2048+2x77x2048+8x154x2048-y=1x2816+2x2816+8x2816.trt
Profile 0:
	sample = [(1, 4, 96, 96), (2, 4, 128, 128), (8, 4, 128, 128)]
	timesteps = [(1,), (2,), (8,)]
	encoder_hidden_states = [(1, 77, 2048), (2, 77, 2048), (8, 154, 2048)]
	y = [(1, 2816), (2, 2816), (8, 2816)]
	latent = [(-1946005248), (-1946001664), (-1945988864)]

*** Error completing request
*** Arguments: ('task(nfpm4ighzggugtr)', 'a girl', '', [], 25, 'DPM++ 2M SDE Karras', 1, 1, 7, 1024, 1024, False, 0.7, 2, 'R-ESRGAN 4x+ Anime6B', 0, 0, 0, 'Use same checkpoint', 'Use same sampler', '', '', [], <gradio.routes.Request object at 0x000002250CB56E60>, 0, False, 'sd_xl_refiner_1.0_0.9vae.safetensors [8d0ce6c016]', 0.7, -1, False, -1, 0, 0, 0, False, 'MultiDiffusion', False, True, 1024, 1024, 96, 96, 48, 1, 'None', 2, False, 10, 1, 1, 64, False, False, False, False, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 3072, 192, True, True, True, False, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x000002250CBBBE50>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x000002250CBB8C70>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x000002250A6F5AB0>, '无(None)', False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, False, None, None, False, None, None, False, None, None, False, 50) {}
    Traceback (most recent call last):
      File "D:\kkkkk\release\SD_webui_with_aki_launcher_dev\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "D:\kkkkk\release\SD_webui_with_aki_launcher_dev\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "D:\kkkkk\release\SD_webui_with_aki_launcher_dev\modules\txt2img.py", line 55, in txt2img
        processed = processing.process_images(p)
      File "D:\kkkkk\release\SD_webui_with_aki_launcher_dev\modules\processing.py", line 734, in process_images
        res = process_images_inner(p)
      File "D:\kkkkk\release\SD_webui_with_aki_launcher_dev\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 42, in processing_process_images_hijack
        return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
      File "D:\kkkkk\release\SD_webui_with_aki_launcher_dev\modules\processing.py", line 869, in process_images_inner
        samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
      File "D:\kkkkk\release\SD_webui_with_aki_launcher_dev\modules\processing.py", line 1145, in sample
        samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
      File "D:\kkkkk\release\SD_webui_with_aki_launcher_dev\modules\sd_samplers_kdiffusion.py", line 235, in sample
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "D:\kkkkk\release\SD_webui_with_aki_launcher_dev\modules\sd_samplers_common.py", line 261, in launch_sampling
        return func()
      File "D:\kkkkk\release\SD_webui_with_aki_launcher_dev\modules\sd_samplers_kdiffusion.py", line 235, in <lambda>
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "D:\kkkkk\release\SD_webui_with_aki_launcher_dev\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\kkkkk\release\SD_webui_with_aki_launcher_dev\repositories\k-diffusion\k_diffusion\sampling.py", line 626, in sample_dpmpp_2m_sde
        denoised = model(x, sigmas[i] * s_in, **extra_args)
      File "D:\kkkkk\release\SD_webui_with_aki_launcher_dev\python\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
        return self._call_impl(*args, **kwargs)
      File "D:\kkkkk\release\SD_webui_with_aki_launcher_dev\python\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
        return forward_call(*args, **kwargs)
      File "D:\kkkkk\release\SD_webui_with_aki_launcher_dev\modules\sd_samplers_cfg_denoiser.py", line 169, in forward
        x_out = self.inner_model(x_in, sigma_in, cond=make_condition_dict(cond_in, image_cond_in))
      File "D:\kkkkk\release\SD_webui_with_aki_launcher_dev\python\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
        return self._call_impl(*args, **kwargs)
      File "D:\kkkkk\release\SD_webui_with_aki_launcher_dev\python\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
        return forward_call(*args, **kwargs)
      File "D:\kkkkk\release\SD_webui_with_aki_launcher_dev\repositories\k-diffusion\k_diffusion\external.py", line 112, in forward
        eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
      File "D:\kkkkk\release\SD_webui_with_aki_launcher_dev\repositories\k-diffusion\k_diffusion\external.py", line 138, in get_eps
        return self.inner_model.apply_model(*args, **kwargs)
      File "D:\kkkkk\release\SD_webui_with_aki_launcher_dev\modules\sd_models_xl.py", line 37, in apply_model
        return self.model(x, t, cond)
      File "D:\kkkkk\release\SD_webui_with_aki_launcher_dev\python\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
        return self._call_impl(*args, **kwargs)
      File "D:\kkkkk\release\SD_webui_with_aki_launcher_dev\python\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
        return forward_call(*args, **kwargs)
      File "D:\kkkkk\release\SD_webui_with_aki_launcher_dev\modules\sd_hijack_utils.py", line 17, in <lambda>
        setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
      File "D:\kkkkk\release\SD_webui_with_aki_launcher_dev\modules\sd_hijack_utils.py", line 28, in __call__
        return self.__orig_func(*args, **kwargs)
      File "D:\kkkkk\release\SD_webui_with_aki_launcher_dev\repositories\generative-models\sgm\modules\diffusionmodules\wrappers.py", line 28, in forward
        return self.diffusion_model(
      File "D:\kkkkk\release\SD_webui_with_aki_launcher_dev\python\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
        return self._call_impl(*args, **kwargs)
      File "D:\kkkkk\release\SD_webui_with_aki_launcher_dev\python\lib\site-packages\torch\nn\modules\module.py", line 1568, in _call_impl
        result = forward_call(*args, **kwargs)
      File "D:\kkkkk\release\SD_webui_with_aki_launcher_dev\modules\sd_unet.py", line 89, in UNetModel_forward
        return current_unet.forward(x, timesteps, context, *args, **kwargs)
      File "D:\kkkkk\release\SD_webui_with_aki_launcher_dev\extensions\Stable-Diffusion-WebUI-TensorRT\scripts\trt.py", line 91, in forward
        tmp = torch.empty(
    torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 12.46 GiB. GPU 0 has a total capacty of 23.99 GiB of which 10.77 GiB is free. Of the allocated memory 1.72 GiB is allocated by PyTorch, and 1.06 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

---

**Comment by contentis** [comment] 2023-10-19 13:02
Duplicate of #48

**Closed** 2024-01-02 08:44 UTC
Labels: bug, duplicate
