### ISSUE TITLE
Please write a proper howto/readme, which doesnt leave out needed information

### ISSUE THREAD

**Issue by makedir** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#33] opened 2023-10-18 06:30 UTC
It is totally not obvious where the "Generate Default Engines button" is. Where is it inside the AUTOMATIC1111 web gui?

**Comment by makedir** [comment] 2023-10-18 06:36
What TensorRT tab? Where? No word from a TensorRT tab in the readme. I dont have a "TensorRT tab". I did this:

Start the webui.bat
Select the Extensions tab and click on Install from URL
Copy the link to this repository and paste it into URL for extension's git repository
Click Install

Restarted AUTOMATIC1111, no word of restarting btw in the readme. And I now get these errors starting AUTOMATIC1111:

![image](https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/assets/6721083/98a79f73-8fe5-469b-9fb9-21f141856b1a)
![image](https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/assets/6721083/cfc51b3e-aed6-4da7-9ad9-fb7e0d5d4b8d)

**Comment by makedir** [comment] 2023-10-18 07:34
> #12

That is a really long debate for just 1 day. So what is the conclusion to it? It doesnt work with stable AUTOMATIC1111 and you need dev build, and no word about it in the readme or install guide?

Also the button I see is just this one:

![image](https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/assets/6721083/3e177025-821d-4e44-a608-d82762e35c26)

Is the "Generate Default Engines button" missing because of the errors above?

**Comment by Vuldorak2** [comment] 2023-10-18 07:39
I'm on dev ^^, no error but no button

**Comment by contentis** [comment] 2023-10-18 10:27
> It is totally not obvious where the "Generate Default Engines button" is. Where is it inside the AUTOMATIC1111 web gui?

My bad, this got lost. I fixed it now in the `hot_fix` branch.

> What TensorRT tab? Where? No word from a TensorRT tab in the readme. I dont have a "TensorRT tab". I did this:

This is caused by an install issue. Working on a fix right now. In the meantime you can follow this: https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/issues/27#issuecomment-1767570566

**Comment by prusswan** [comment] 2023-10-18 14:40
Apparently there is a guide on nvidia's support website: https://nvidia.custhelp.com/app/answers/detail/a_id/5487/%7E/tensorrt-extension-for-stable-diffusion-web-ui

Link should be added to the repo

**Comment by makedir** [comment] 2023-10-18 18:01
So another false information in the readme. The button is named "Export Default Engine" not "Generate Default Engines".

**Comment by contentis** [comment] 2023-10-18 22:13
@makedir Should be fixed now in the master.

**Comment by makedir** [comment] 2023-10-20 05:24
@contentis what exactly is now fixed? I installed a new automatic1111 dev branch, tried to install again Stable-Diffusion-WebUI-TensorRT and now again get this:

![image](https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/assets/6721083/ceb0d78f-0f57-4661-955d-36085f756eac)

**Closed** 2024-01-02 08:42 UTC
Labels: bug, duplicate
